# Site settings
title: CHENG ZHAN
email:  cz23@mail.ustc.edu.cn
description: > # this means to ignore newlines until "baseurl:"
  This is CHENG ZHAN's Homepage (cheng zhan)
baseurl: "/blog/" # the subpath of your site, e.g. /blog/
url: "https://enchanted23.github.io" # the base hostname & protocol for your site
twitter_username: Enchanted
github_username:  Enchanted23

# Build settings
markdown: kramdown
