title: CHENG ZHAN
description: > # this means to ignore newlines until "baseurl:"
  CHENG ZHAN | 程湛
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://enchanted23.github.io" # the base hostname & protocol for your site
# Build settings
markdown: kramdown

facebook: 
  app_id: 

logo: "../css/2016_style/img/icon-large.png"

social: 
  name: Your Facebook Page
  link: "https://www.facebook.com/zhan.cheng.9889"

# basic information of myself and my education experiences
people:
- name: Cheng Zhan
  pic: 1
  position: Senior Student Majoring In Computer Science
  social:
    - title: wechat
      url: 
    - title: facebook
      url: https://www.facebook.com/zhan.cheng.9889
    - title: github
      url: https://github.com/Enchanted23

- name: University Of Science And Technology Of China
  pic: 2
  position: College
  social:
    - title: university
      url: http://www.ustc.edu.cn
    - title: google
      url: https://en.wikipedia.org/wiki/University_of_Science_and_Technology_of_China

- name: Chongqing Nankai Middle School
  pic: 3
  position: High School
  social:
    - title: google
      url: https://en.wikipedia.org/wiki/Chongqing_Nankai_Secondary_School

google_site_verification: googleXXXXXXXXXXXXXXXX.html

include: ['_2016_pages', '_2017_pages']

gems:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com
  - title: twitter
    url: https://twitter.com

# Build settings
markdown: kramdown
permalink: pretty