## Base settings ##
url: "https://enchanted23.github.io" # the base hostname & protocol for your site
description: > # this means to ignore newlines until "baseurl:"
    CHENG ZHAN | 程湛

title: CHENG ZHAN
email: cz23@mail.ustc.edu.cn

logo: "../css/_style/img/icon-large.png"

# basic information of myself and my education experiences
people:
- name: Cheng Zhan
  pic: 1
  position: Senior Student Majoring In Computer Science
  social:
    - title: wechat
      url: 
    - title: facebook
      url: https://www.facebook.com/zhan.cheng.9889
    - title: github
      url: https://github.com/Enchanted23

- name: University Of Science And Technology Of China
  pic: 2
  position: College
  social:
    - title: university
      url: http://www.ustc.edu.cn
    - title: google
      url: https://en.wikipedia.org/wiki/University_of_Science_and_Technology_of_China

- name: Chongqing Nankai Middle School
  pic: 3
  position: High School
  social:
    - title: google
      url: https://en.wikipedia.org/wiki/Chongqing_Nankai_Secondary_School

include: ['_site_pages']

gems:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/
  - title: facebook
    url: https://www.facebook.com/
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/
  - title: bitbucket 
    url: http://bitbucket.org/
  - title: github
    url: http://github.com/

# Build settings
markdown: kramdown
permalink: pretty